### ISSUE TITLE
Bug - 1.16.4

### ISSUE THREAD

**Issue by Blugori** [dainxt/WeaponThrow#1]
Hi, I ran into a bug while using weapon throw 2.9
(Minecraft : 1.16.4, Forge : 35.0.1)
My keyboard key assigned to "drop selected item" will trigger the animation like I am about to throw an axe, even if the key assigned to weapon throw have no relation to this previous key.
When it happen, my character walks slower, and the model have the right arm up in the air.
To stop this animation and the slow effect, I have to press the key assigned to weapon throw with an axe in my hand.
![2020-11-05_14 09 36](https://user-images.githubusercontent.com/66573974/98245005-99ad4600-1f70-11eb-8195-75fd8131ac04.png)
![key8](https://user-images.githubusercontent.com/66573974/98245045-a3cf4480-1f70-11eb-9518-092b9b370312.PNG)
![keyQ](https://user-images.githubusercontent.com/66573974/98245049-a6319e80-1f70-11eb-9077-c00a147875ca.PNG)

Best regards

**Comment by dainxt** [comment]
Fixed, thanks for the information
