### ISSUE TITLE
Mod not Loading/ Mod Failed to Load

### ISSUE THREAD

**Issue by Coraline77447** [dainxt/WeaponThrow#11]
Minecraft: 1.17.1
Forge: 37.0.34
Weapon Throw: 4.6

I'm experiencing an unknown issue with Weapon Throw as of it's latest 1.17 release (4.6)...
During mod loading I get stuck with a white screen without it changing to the red mojang screen and I had the game output open during launch and the info wasn't going past 26 or so...
I can't really provide a crash report since the issue is happening during the early mod loading process and I had to close the game while it wasn't responding during the mod loading process...

Even tho there's really no crash report but I could at least provide the debug log(s);
[debug.log](https://github.com/dainxt/WeaponThrow/files/6990957/debug.log)

Why the debug log(s)? Because in the latest log won't really provide the answers just like there's really no crash report...

Here's the latest log anyways and I took a look in it and as I've said that there's really nothing in it that tells us what's wrong with Weapon Throw's latest version for 1.17;
[latest.log](https://github.com/dainxt/WeaponThrow/files/6990993/latest.log)

Anyways, now I'll have to try to use version 4.5 to see if it'll work...

UPDATE: I'm starting to suspect that what's causing this isn't Weapon Throw and another mod (Advancement Plauqes).

The issue is coming from a different mod that used to work in previous forge versions except for the latest forge version which fixes the version checker. 

So now with the version checker properly working, now one of the mods in my 1.17.1 mods folder isn't working anymore...

Right now I'm trying to figure out which mod i have is the cooperate which I'm not suspecting Weapon Throw to be one of them....

I've came to the conclusion that the latest release of Weapon Throw isn't causing the issue, the issue is coming from 15 other mods that used to work in previous forge versions (37.0.31 to 37.0.33) but now thanks to whatever the forge devs fixed is causing 15/50+ mods in my mods folder to malfuncion/fail or no longer work/load...

So either you or I can close this report cause the issue has nothing to do with Weapon Throw and why I'd thought that Weapon Throw and Advancement Plaques (owned by someone else btw) were at fault when that's not the case....

I should've checked exactly which mod(s) are really at fault before making exceptions and this report...
Sorry for wasting your time....

**Comment by dainxt** [comment]
Clean report, hopefully you will find the issue for your other mods.

**Comment by Coraline77447** [comment]
Heres what I've found out about the problem is that beyond 37.0.33 that 15 mods were killed after installing forge 37.0.34.

What I mean by that is that they just wont work now, even after downgrading forge to 37.0.33 cause of the changes that were made in 37.0.34 which was this: "Ensure that all render targets in a PostChain use the same format"

Cause of this those 15 mods (not including Weapon Throw and Advancement Plaques) doesn't use the same formatting in a PostChain since they probably weren't using the correct formatting in a PostChain before the forge 37.0.34.

After installing forge 37.0.34 and ran it for the first time that those 15 mods died instantly since they used to work before installing 37.0.34.

Thought that what was the problem was the versioning of those 15 mods as of what forge version they were using but now its cause of what I'd explained above.

So that's why the screen never went to the Mojang screen during mod loading.
