### ISSUE TITLE
Tidy up config in 1.16.5

### ISSUE THREAD

**Issue by Nika-m** [dainxt/WeaponThrow#14]
Its a bit hard to configure mod, I dont fully understand how multipliers work, and they are not sorted in any order,
sorting similar configurations and adding some little descriptions in config would be great

**Comment by dainxt** [comment]
Added more information and organized the multipliers in 4.5, Also there's an example with the multipliers on the curseforge page.

**Comment by Nicknaem** [comment]
> Added more information and organized the multipliers in 4.5, Also there's an example with the multipliers on the curseforge page.

oh yeah, thank you alot
