### ISSUE TITLE
minecraft crash-log when running minecraft

### ISSUE THREAD

**Issue by Whataheckisasonic** [dainxt/WeaponThrow#16]
---- Minecraft Crash Report ----
// My bad.

Time: 14/09/2021 18:23
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'weaponthrow'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:34)
	at net.minecraft.class_310.<init>(class_310.java:457)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/client/rendering/v1/EntityRendererRegistry
	at com.dainxt.weaponthrow.handlers.RenderRegistry.registerRenderers(RenderRegistry.java:10)
	at com.dainxt.weaponthrow.ClientMod.onInitializeClient(ClientMod.java:17)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.client.rendering.v1.EntityRendererRegistry
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:175)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 14 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)

-- Patchouli Book Info --
Details:
	Patchouli open book context: n/a
Stacktrace:
	at net.minecraft.class_128.handler$bmd000$fillPatchouliContext(class_128.java:521)
	at net.minecraft.class_128.<init>(class_128.java:37)
	at net.minecraft.class_128.method_560(class_128.java:267)
	at net.minecraft.client.main.Main.main(Main.java:185)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Initialization --
Details:

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 559180424 bytes (533 MiB) / 1912602624 bytes (1824 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 3 3200G with Radeon Vega Graphics    
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: Zen / Zen+
	Frequency (GHz): 3,59
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: NVIDIA GeForce GTX 1050 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095,00
	Graphics card #0 deviceId: 0x1c82
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7111
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 2,67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192,00
	Memory slot #1 clockSpeed (GHz): 2,67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 20428,71
	Virtual memory used (MB): 14573,96
	Swap memory total (MB): 4096,00
	Swap memory used (MB): 175,30
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		achievement_plates: Achievement Plates 1.1
		additionaladditions: Additional Additions 2.1.1
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		advancementplaques: Advancement Plaques 1.4.0
		alaskanativecraft: Alaska Native Craft 1.3.1
		animal_feeding_trough: Animal Feeding Trough 1.0.2
		anthropophagy: Anthropophagy 1.17-4
		antiqueatlas: Antique Atlas 6.0.0-fabric-mc1.17.1
		apoli: Apoli 1.0.3
		apples: Apples & Carrots 1.0
		appletreesrev: Apple Trees Rev. 2.2
		arcana2plus: Arcana ++ 0.0.4+1.17-alpha
		arcanus: Arcanus 1.7
		architectury: Architectury 2.3.23
		artifality: Artifality 0.3.3
		artificialcreature: Artificial Creature beta1.00008
		autoconfig1u: Auto Config v1 Updated 3.3.1
		bclib: BCLib 0.3.1
		bedspreads: Bedspreads 1.4.0-1.17
		better_wandering_trader: Better Wandering Trader 1.7.0
		betterstrongholds: YUNG's Better Strongholds 1.17-1.1.1
		blackstonetools: Blackstone Tools 2.0.0+1.17
		boatcontainer: BoatContainer 1.0.0
		boats-and-beeps: Boats and Beeps 1.0.3
		bountiful: Bountiful 1.0.0
		brewable_experience: Brewable Experience 1.1.1
		bright-ore: Bright Ore 0.3.0
		calio: Calio 1.0.1
		cardinal-components: Cardinal Components API 3.1.1
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-block: Cardinal Components API (blocks) 3.1.1
		cardinal-components-chunk: Cardinal Components API (chunks) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		cardinal-components-item: Cardinal Components API (items) 3.1.1
		cardinal-components-level: Cardinal Components API (world saves) 3.1.1
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 3.1.1
		cardinal-components-util: Cardinal Components API (utilities) 3.1.1
		cardinal-components-world: Cardinal Components API (worlds) 3.1.1
		carrier: Carrier 1.8.0
		cauldrons: Cauldrons 1.1.1
		charm: Charm 3.3.2
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 5.0.37
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_focamacho_sealconfig: sealconfig 1.2.2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		compostable-rottenflesh: Compostable Rotten Flesh 1.0.0
		cozy_camping: Cozy Camping 1.0.0-1.17
		crawl: Crawl 0.9.2
		crowdin-translate: CrowdinTranslate 1.3+1.17
		danceofgrowth: Twerk / Crop Dusting Mod 1.0
		day_dream: Day Dream 1.0.2
		de_javagl_obj: obj 0.3.0
		dimores: DimensionalOres 1.0.1
		dualwielding: Dual Wielding 1.0.6
		earthtojavamobs: Earth2Java 1.7.3+1.17
		easyupdate: Easy Update 1.0.1
		ecs: Elytra/Chestplate Swapper 1.2.0-MC1.17
		eldritch_mobs: Eldritch Mobs 1.9.2
		elytraboosters: Elytra Boosters Mod 1.2.0
		elytracrafting: Elytra Crafting 4.1.0
		emeraldextendedfabric: EmeraldExtendedFabric 1.0
		enchant_giver: Enchant Giver 1.1.0
		endermenarefriends: Endermen Are Friends 1.1-mc1.17-fabric
		enva: Environmental Armor 1.4.1
		environmentz: EnvironmentZ 1.1.4
		evolve: Evolving origins 1.0.0
		expcontainer: Experience Container [XP] 1.15.2
		extended_armor_bars: Extended Armor Bars 1.1.0
		extraorigins: Extra Origins 1.17-6
		fabric: Fabric API 0.37.2+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.2.0+2b5c62d018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+c345aea818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b446318
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.4+2e8bd82f18
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b446318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.9+a722d8c018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+6cefd57718
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b446318
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+a02b446318
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.4+kotlin.1.5.30
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+2e8bd82f18
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa13
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab612118
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+5f02c96918
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+a02b446318
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.0+a02b446318
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+a02b446318
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afa18
		fabric-rendering-v1: Fabric Rendering (v1) 1.7.0+2e8bd82f18
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+155f865c18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b446318
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b446318
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.0.0+3fe3c3f518
		fabricloader: Fabric Loader 0.11.6
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fiber: fiber 0.23.0-2
		fishonaleash: Fish on a Leash! 1.17-1.0.0
		gateofbabylon: Gate Of Babylon 1.5.0-1.17
		gbfabrictools: GBfabrictools 1.3.4+1.17
		geckolib3: Geckolib 3.0.13
		geodes: More Geodes 1.0.4
		gizmos: Gizmos 1.4.0
		glowingbanners: Glow Banners 1.0.2
		goldensteak: Goldensteak 1.0.5
		golemsgalore: Golems Galore 1.0.2+mc.1.17
		gottaclimbfast: Gotta Climb Fast! 1.17-3.0-fabric
		graveyard: The Graveyard 1.0
		greater_eye: Greater Eye of Ender 1.2.8
		helpwanted: Help Wanted 1.1.0
		hookshot: Hookshot 18.0
		interactic: Interactic 0.1.5-1.17
		irishwolves: Irish Wolves 1.0.0+java.16
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		kambrik: Kambrik 1.1.0
		kibe: Kibe 1.8.1-BETA+1.17
		lakeside: Lakeside 1.1.0+1.17
		lambdynlights: LambDynamicLights 2.0.2+1.17
		libblockattributes: LibBlockAttributes 0.9.0
		libblockattributes_core: LibBlockAttributes (Core) 0.9.0
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.9.0
		libblockattributes_items: LibBlockAttributes (Items) 0.9.0
		libgui: LibGui 4.1.4+1.17.1
		libninepatch: LibNinePatch 1.1.0
		magick: Magick: Potions and Pearls 1.0.5
		malusphaethusa: Malus Phaethusa 1.0.1
		mcdar: MC Dungeons Artifacts 1.4.1
		midnightlib: MidnightLib 0.2.4
		minecraft: Minecraft 1.17.1
		mm: Manningham Mills 2.3
		modid: Portable Jukebox 1.1.1
		modmenu: Mod Menu 2.0.3
		morebannerfeatures: More Banner Features 1.0.7
		moretotems: More Totems 2.8.0
		mostructures: Mo' Structures 1.2.1-1.17
		mtools: MagmaTools 0.0.1
		multipart-entities: Multipart Entities 1.0.2
		myron: Myron 1.6.0
		mythic-mounts: Mythic Mounts 1.17.1-1.2
		nauticality: Nauticality 0.1.2
		nbtcrafting: NBT Crafting 2.0.19+mc1.17
		nears: Nears 1.1.2
		neutrino: Neutrino 0.2.0
		npcvariety: NPC Variety 2.1.2
		nyfsquivers: Nyf's Quivers Fabric-0.2.6
		oauth-fabric: Oauth 1.0
		obsdncontainer: Obsidian Container [Experience Container Addon] 1.0.2
		omega-config: OmegaConfig 1.0.8
		org_apache_httpcomponents_httpclient: httpclient 4.5.10
		org_apache_httpcomponents_httpcore: httpcore 4.4.12
		org_apache_httpcomponents_httpmime: httpmime 4.5.10
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.30
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.30
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.2.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.2.2
		org_objenesis_objenesis: objenesis 3.2
		origins: Origins 1.0.2
		origins-classes: Origins: Classes 1.2.2
		oxidized: Oxidized 1.2.0
		parry: Parry 1.2
		patchouli: Patchouli 1.17-54-FABRIC
		pax: Pax 1.0.0
		pehkui: Pehkui 2.2.1+1.14.4-1.17
		pettable: Pettable 1.2.0
		pigsteel: Pigsteel Mod 1.6.5
		plantinajar: Plant In A Jar 2.2.2
		platypus: Platypuses 1.0.0
		playerabilitylib: Pal 1.3.0
		ppp: Port's Parrots Plus 1.3.0
		pugh_lib: Pugh Lib ${version}
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		rejmov: Rejuvenation Mod 1.0.0-1.17+
		repurposed_structures: Repurposed Structures 2.3.1+1.17.1
		resourceful_tools: Resourceful Tools 1.1.19
		ringsofascension: Rings of Ascension 1.0.1
		ripplers: Ripplers 0.3
		roughlyenoughitems: Roughly Enough Items 6.0.267-alpha
		scorch: Scorch 1.0.2
		seasons: Fabric Seasons 1.2.2-BETA+1.17
		secondchance: Second Chance 1.0.0
		selene: Selene 1.0.1+1.17.1
		skinswapper: Skin Swapper 2.1.0
		skylorlib: SkyLib 1.0.4
		spruceui: SpruceUI 3.2.0+1.17
		stepup: StepUp 1.17.1-fabric0.36.1-1.1
		stoneholm: Stoneholm 1.3
		structurized: Structurized 1.3.0
		things: Things 0.2.3
		tokenablefurnaces: Tokenable Furnaces 1.1.3
		torohealth: ToroHealth Damage Indicators 1.17.1-fabric-12
		totemicoverhaul: Totemic Overhaul 1.2
		totemmod: Wither Totems Mod 0.3.2
		trinkets: Trinkets 3.0.2
		trumpet-skeleton: Trumpet Skeleton 1.1.4
		unsaddleeeee: Unsaddleeeee 1.0+mc1.17-Fabric
		untitledduckmod: Untitled Duck Mod 0.3.0
		villager_see_villager_do: Villager See, Villager Do 1.0.5+MC1.17-1.17.1
		visuality: Visuality 0.1.1
		waystones: Waystones 2.0.3
		weaponthrow: Weapon Throw 1.17.1-1.2
		yatm: Yet Another Tweaks Mod 0.1.1
		yungsapi: YUNG's API 1.17-Fabric-16
	Launched Version: fabric-loader-0.11.6-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by dainxt** [comment]
Update your fabric api
