### ISSUE TITLE
Love the idea, but can you make the throw a little more snappy?

### ISSUE THREAD

**Issue by Mr-Syntax** [dainxt/WeaponThrow#17]
What i mean is in my pack this one
https://www.curseforge.com/minecraft/modpacks/chosencraft
when i try to throw sometimes when i release it will still keep building up and i have to jump to release it??

i dunno if this is a bug or just unintentional, but it would be awesome if it would just be a straight hold and release button so as soon as you release you throw

**Comment by dainxt** [comment]
I have been testing your modpack, the rebind to the mouse buttons is provoking the issue, this is not presented if you use a keyboard key or the default keybinding. Ill try to patch it and update if it is solved.

**Comment by dainxt** [comment]
Added proper support to mouse buttons in 5.1

**Comment by Mr-Syntax** [comment]
thank you so much bro its awesome!
