### ISSUE TITLE
Physics Enhancements

### ISSUE THREAD

**Issue by Nicknaem** [dainxt/WeaponThrow#18]
at the moment items should be whitelisted, to have default multipliers assigned thats a big problem
I want all minecraft items except weapons & tools to have assigned default base damage and velocity multipliers

by default players should be able to throw all kind of items

I think default throw key : ALT, its much more comfortable

holding down ctrl + alt should repeatidly throw stack items one by one, now users have to smash throw key 

I think in mod description you should mention that modified multiplier adds up to base multiplier
eg: when base damage multiplier is : 2
and modified damage multiplier is : 4
in this case modified damage muiltiplier is 6, at first I couldn't figure out what was happening I thought it should be 4

**Comment by dainxt** [comment]
Yep, thats how it works, the whitelist is only for weapons that arent recognized or for very specific items, go to experimental features if you want to enable throwing all items. 

Also Keybinds cant contain 2 modifiers as it counts as a OS Specific Keybind.

About the example, ill do the changes

**Comment by Nicknaem** [comment]
I have experimental feature throwing all items set to true, base velocity and modified velocity multipliers does apply to all items, but base damage and modified damage multipliers doesnot apply to all items untill I whitlelist all of the minecraft items, I think it shoud apply to all items as base velocity multiplier works.
and also I wanted to say throwing item directly to the flat surface makes item rotate too much time, when throwing item at wall or throwing it up, it works well, items normally stick to the ground when they fall, but throwing them directly to the ground doesnot look good, I don't know if its possible to optimize that, Im using 1.16.5 version

https://user-images.githubusercontent.com/55950404/137713994-ce1e3375-54cf-4355-81eb-d06274769839.mp4

t

**Comment by dainxt** [comment]
Probably fixed the default damage part, and the boncy issue in 5.2

**Comment by Nicknaem** [comment]
default damage part still doesnot apply on items, when  throwing all items is set to true.
bouncy items are fixed, but on flat surfaces, often times items bounce back instead of bouncing forward
![Animation3](https://user-images.githubusercontent.com/55950404/138050948-4b52e7d8-d5ee-4a4a-9914-870b43072f1d.gif)

**Comment by dainxt** [comment]
I've tested the default damage and works as intended for me, fixed the bounce direction

**Comment by Nicknaem** [comment]
it works, needed to remove old config file, awesome work, players are having so much fun using your mod, thanks
