### ISSUE TITLE
Setting "castTimeInTicks" to 0 breaks rendering (Fabric version)

### ISSUE THREAD

**Issue by KermitzeFraud** [dainxt/WeaponThrow#19]
Setting "castTimeInTicks" to 0 in config file breaks rendering when a weapon is thrown, game didn't crash. Exit to main menu and load the same world or a different one doesn't fix the problem, restarting does, until a weapon is thrown. Setting "castTimeInTicks" to at least 1 resolves the issue.

I do have mods that alter world, lighting and items rendering:
- Sodium
- Lithium
- Phosphor
- Interactic (has option to alter item rendering)

**Comment by dainxt** [comment]
Fixed in 5.2 for Forge and in 1.3 in Fabric
