### ISSUE TITLE
Add a Ingame config from Mod menu mod(for Fabric)

### ISSUE THREAD

**Issue by tankyap** [dainxt/WeaponThrow#20]
Actually, it would be pretty annoying if you wanted to cofig it, because you need to restart the game and cofig in cofig file then test it over and over till you find a perfect config for you, please add it for fabric since it was existed just for fabric.

> [here's the Mod menu mod page if you want to know more about it.](https://www.curseforge.com/minecraft/mc-mods/modmenu)

**Comment by dainxt** [comment]
Tbh, The mod would have included one but the implementations takes time (Do the translations etc)... Probably I will include it in a future.

**Comment by dainxt** [comment]
Added in 1.4
