### ISSUE TITLE
Animation breaks in multiplayer sessions (Forge)

### ISSUE THREAD

**Issue by ghost** [dainxt/WeaponThrow#21]
Bug
Animation of the throwing of the weapon breaks when more than 1 user is on the server. Instead of a pull-back animation, the weapon just starts shaking until released. Weird thing is when only 1 person is on the server, the pull-back animation starts working again.

Modlist
![modlist](https://user-images.githubusercontent.com/93447646/139555076-367c4959-f068-4a46-9ed2-c61e4134b4b5.png)

Logs
[logs.txt](https://github.com/dainxt/WeaponThrow/files/7447434/logs.txt)

Couldn't find anything on WeaponThrow when rebooting the server in the console, but here are the logs.

**Comment by dainxt** [comment]
Fixed in 5.4
