### ISSUE TITLE
Incompatible with Security Craft 1.18.1 v1.9.0.2-beta1

### ISSUE THREAD

**Issue by onemancantwo** [dainxt/WeaponThrow#24]
The most recent versions as of 2/17/22 of both [Security Craft](https://www.curseforge.com/minecraft/mc-mods/security-craft) and your mod Weapon Throw are incompatible

Here's the crash report:
[crash-2022-02-17_20.33.36-client.txt](https://github.com/dainxt/WeaponThrow/files/8094740/crash-2022-02-17_20.33.36-client.txt)

**Comment by dainxt** [comment]
Fixed in 1.18.1-5.6, confirm it if it is possible.
