### ISSUE TITLE
Everything except for player UI goes invisible after respawning; world can still be interacted with, nothing printed in logs, seems to be an entirely client-sided issue.

### ISSUE THREAD

**Issue by NovaN4** [dainxt/WeaponThrow#3]
I've been using this mod since the initial release of the first 1.16 version and I finally found out that it's actually the culprit of a game-breaking issue.

On death, there's a chance (I think, it's probably situational or it just happens every time) that you won't be able to see anything at all. Leaving and rejoining the world doesn't fix this, reloading textures doesn't fix this, only fully closing and reopening your game does. This is a problem for people like me with large mod packs that take ~10 minutes to start up, as most people don't want to wait 10 minutes to restart their game every time they die.

It might be an incompatibility issue, I haven't gotten around to testing to see if the issue appears with just this mod only. However, I know that I had 220 mods and now I have 219 and the issue's gone after removing weapon throw (took me around 5 hours of doing the "remove half, remove half, remove half" strategy).

If you see this, it would be much appreciated if you could look into the issue. Thank you :D

(Reposted from Curseforge, as I figure leaving it on the issue tracker would be a hell of a lot more useful)

Edit: To replicate simply load up a world and type /kill. If it doesn't work, type /kill again until the issue happens. If it never happens, it's confirmed to be an incompatibility with another mod.

**Comment by dainxt** [comment]
Got some cleaning on 3.3 that could fix this issue. I will leave this issue open anyways if the problem persist.

**Comment by NovaN4** [comment]
Problem's fixed for me. Closing issue, you can reopen it in the future if it becomes a problem again.
