### ISSUE TITLE
Items Disappearing From Inventory

### ISSUE THREAD

**Issue by Coraline77447** [dainxt/WeaponThrow#4]
Hi, I'm here to report an issue that whenever I throw an item out of my inventory onto the ground that the item instantly vanishes and even dragging out items from the inventory onto the 
ground instantly disappears from the inventory, took me a while to figure out which mod out of the 70 mods that I'm playing with, I originally thought that a mod called More Powerful Gamerules mod was the cause of this but its not, then I've suspected some other mods that was the cause of this issue but none of them weren't the corporate as well, so earlier today (like two hours ago or so) when I wanted to give my guard villager some iorn armor (btw its a mod that let's you recruit villagers to become guards of the village) that the iron armor just vanishes when I dropped the armor from my inventory (this also happened on a different modded survival world that I had when I was trying to make some villagers breed by tossing them half a stack of bread and the bread was disappearing when I was dropping the bread from my inventory). Then I had to finally figure out which mod out of the 70 mods that I was playing with that was causing this issue, so I took out all of the mods and I'd put the mods back into my mods folder one at a time then 2 at a time then groups of them at a time and had made a test world till I had half of 70 mods then I went back onto the modded world that I'm currently playing on and came down to a mod called Wonderful Enchantments and Weapon Throw, when I came back onto the world for the last time and tossed an iorn sword it instantly vanishes and I was saying over and over "its Weapon Throw!" "its definitely Weapon Throw!" Btw you don't even know how happy I am right now to FINALLY found out which mod was causing this issue that I've been having ever since the problem began but now I'm not happy that it's from this good mod cause now I'm not going to reinstall this mod till you fix the item disappearing bug... P.S. I actually don't mind this bug when it comes down to tossing useless junk from my inventory but say I were to have an enchanted netherite sword or an enchanted bow or anything that's worth keeping that at any unfortunate moment that I were to accidentally toss the enchanted item out of my inventory and it instantly vanishes forever. I would've been so mad if that were to happen but its not going to happen cause I'm not going to have Weapon Throw installed till this item disappearing bug gets fixed. (I know that I've said this alot of times before but I'm gonna say it again that I really hope that this report ain't too much to read!...

**Comment by dainxt** [comment]
Probably fixed on 3.5 You can close this issue if its solved. Or comment back if theres any changes. Thank you for taking your time to report the bug.

**Comment by Coraline77447** [comment]
I'll get it and install it before I start my next modded minecraft play session since I'm always looking for updates to mods that I'm playing with before I even start playing modded minecraft except that I'm not going to be playing modded minecraft with mods that are in Alpha or Beta version like Bookshelf (library mod) is in Alpha right now as of its current version. Btw your welcome. Also thank you for your great work and the great mod, along side with another one that allows us to dual wield our weapons almost like a 1.12.2 mod called Better Combat Reborn and almost like a really old mod that is well known but no longer supported and possibly dead but idk if there's truly any other mod out there that allows us to throw our swords and axes at our foes (I know that you may know what I mean by "us" "our" but I want to say that what I mean by "us" "our" is other minecrafters/people not just me who uses your mod). I'm not gonna close this yet cause I still need to test out the latest version of Weapon Throw when I get the update before I start my next modded minecraft play session just in case the issue still exists but somewhat fixed in a way cause ya never know if the problem is fixed or not truly fixed/gone till I and everyone else tries it out.

**Comment by dainxt** [comment]
Ok, I'll close this issue
