### ISSUE TITLE
weaponthrow enchantments doesn't work with tetra tools

### ISSUE THREAD

**Issue by brandonmaster590** [dainxt/WeaponThrow#7]
Hey! it's me again and as the title said the enchantments from weapon throw doesn't work with tetra worktable it been an issue seen my last comment, because of my wording (English is my second language btw) you misunderstand my problem so that's my fault for not giving enough info about my problem but I'm patient so you can enjoy the holiday with your friends and families.
HAPPY NEW YEAR!

**Comment by brandonmaster590** [comment]
hello again just coming by to check in to see if your doing well hope you're doing great over there and I keep getting these feeling like I'm bothering you every time I made a post here hope you don't mind

**Comment by dainxt** [comment]
Hi, I was just taking some free time. I've just read that custom enchantments have to be added to the tetra configuration. Anyways I will check if there's any problem with that this week. Happy new year and happy holidays.

**Comment by brandonmaster590** [comment]
Ah ok. Just replying so you know that I read it

**Comment by dainxt** [comment]
Partially fixed, ty for waiting. Please reply if it any additional issue.

**Comment by brandonmaster590** [comment]
thank. It working fine now and no bug from what I'm seeing so you can close it
