### ISSUE TITLE
Log Spam

### ISSUE THREAD

**Issue by cybernewtype** [dainxt/WeaponThrow#8]
[Render thread/INFO] [co.da.we.WeaponThrow/]: []
[Render thread/INFO] [co.da.we.WeaponThrow/]: []
[Render thread/INFO] [co.da.we.WeaponThrow/]: []
...

Stopped watching the game log because the log length surpassed 100000 lines.

**Comment by dainxt** [comment]
Sorry, fixed in 4.2
